from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from xaulytics_etl.models import RateRecord


def _safe_inverse(value: float) -> float | None:
    if value == 0:
        return None
    return 1.0 / value


def _infer_unit(quote_code: str) -> str | None:
    if quote_code.startswith("XAU") or quote_code.startswith("XAG") or quote_code in {"XPT", "XPD"}:
        return "troy_ounce"
    # Broad fallback for non-precious metal symbols.
    if quote_code.startswith("X") or quote_code in {"ALU", "IRON", "NI", "ZNC"}:
        return "ounce"
    return None


def _is_primary_quote(quote_code: str, base_currency: str) -> bool:
    # Exclude reciprocal keys generated by API such as USDXAU, USDEUR.
    if quote_code.startswith(base_currency) and len(quote_code) > len(base_currency):
        return False
    return True


def normalize_latest_payload(payload: dict[str, Any]) -> list[RateRecord]:
    base_currency = payload["base"]
    timestamp = payload.get("timestamp")
    pricing_date = datetime.fromtimestamp(timestamp, tz=timezone.utc).date().isoformat() if timestamp else None
    if pricing_date is None:
        raise ValueError("Missing timestamp in latest payload")
    return _normalize_rates(
        rates=payload.get("rates", {}),
        pricing_date=pricing_date,
        base_currency=base_currency,
        source_endpoint="latest",
        source_timestamp=timestamp,
    )


def normalize_timeframe_payload(payload: dict[str, Any]) -> list[RateRecord]:
    base_currency = payload["base"]
    results: list[RateRecord] = []
    for pricing_date, rates in payload.get("rates", {}).items():
        results.extend(
            _normalize_rates(
                rates=rates,
                pricing_date=pricing_date,
                base_currency=base_currency,
                source_endpoint="timeframe",
                source_timestamp=None,
            )
        )
    return results


def normalize_historical_payload(payload: dict[str, Any], endpoint_name: str = "historical") -> list[RateRecord]:
    base_currency = payload["base"]
    timestamp = payload.get("timestamp")
    pricing_date = datetime.fromtimestamp(timestamp, tz=timezone.utc).date().isoformat() if timestamp else None
    if pricing_date is None:
        raise ValueError("Missing timestamp in historical payload")
    return _normalize_rates(
        rates=payload.get("rates", {}),
        pricing_date=pricing_date,
        base_currency=base_currency,
        source_endpoint=endpoint_name,
        source_timestamp=timestamp,
    )


def _normalize_rates(
    rates: dict[str, Any],
    pricing_date: str,
    base_currency: str,
    source_endpoint: str,
    source_timestamp: int | None,
) -> list[RateRecord]:
    normalized: list[RateRecord] = []
    for quote_code, raw_rate in rates.items():
        if not _is_primary_quote(quote_code, base_currency):
            continue
        try:
            quote_per_base = float(raw_rate)
        except (TypeError, ValueError):
            continue
        price_usd = _safe_inverse(quote_per_base)
        if price_usd is None:
            continue
        normalized.append(
            RateRecord(
                pricing_date=pricing_date,
                quote_code=quote_code,
                base_currency=base_currency,
                quote_per_base=quote_per_base,
                price_usd=price_usd,
                unit=_infer_unit(quote_code),
                source_endpoint=source_endpoint,
                source_timestamp=source_timestamp,
            )
        )
    return normalized
